name: guide_me
description: "GuideMe"

publish_to: 'none'
version: 1.0.0+19

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.8.0
  google_maps_flutter: ^2.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  flutter_typeahead: ^5.2.0
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  firebase_core: ^2.27.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  bcrypt: ^1.1.3
  lottie: ^2.7.0
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7
  intl: 0.20.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.5.1
  dropdown_button2: ^2.3.9
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  logger: ^2.5.0
  flutter_flavor: ^3.1.4
  go_router: ^14.7.2
  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.2
  cached_network_image: ^3.4.1
  sliding_up_panel: ^2.0.0+1
  modal_bottom_sheet: ^3.0.0
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.1.2
  path: ^1.8.3
  uuid: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_image_compress: ^2.2.0
  flutter_polyline_points: ^2.1.0
  syncfusion_flutter_pdfviewer: ^29.2.9 #odczytujepdf-regulamin
  flutter_map: ^8.1.1
  vector_map_tiles: ^9.0.0-beta.8
  vector_tile_renderer: ^6.0.0
dev_dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  freezed: ^2.5.8
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  riverpod_generator: ^2.6.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/icons/ikonka.png
    - assets/docs/regulamin.pdf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"