org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
MAPBOX_DOWNLOADS_TOKEN=sk.eyJ1IjoiYm9zaXV1cSIsImEiOiJjbWZ6a3UyejEwM3Y1MnZxdzVhdzMxaTA0In0.2gcqfhco8lgrhd94667xuQ